### ISSUE TITLE
Participant status is not serialized when creating an event

### ISSUE THREAD

**Issue by romass96** [nylas/nylas-java#120]
**Describe the bug**
Participant status is not serialized when creating an event. Invocation of Event.getWritableFields(true) always calls Participant.getWritableFields(false), so status is not present in HTTP request.

**To Reproduce**
Create event and set at least one participant with status = 'YES'
```
Event event = new Event();
// Set all required fields
Participant participant = new Participant("test@gmail.com");
participant.status(Participant.Status.YES);
event.setParticipants(List.of(participant));

application.getClient().account(accessToken).events().create(event, true);
```

**Expected behavior**
Participant status should be sent when creating an event

**SDK Version:**
Version - 1.18.0

**Additional context**
It seems that the bug was made after this commit https://github.com/nylas/nylas-java/commit/d97dec655aecb85ef9861e3909ad58ecb6f0e315

**Comment by mrashed-dev** [comment]
Thanks for catching this bug @romass96! We'll work on this and get back to you with an update.

**Comment by mrashed-dev** [comment]
Thanks for raising this issue @romass96, #124 has been merged into main and a release will be out soon containing the fix.
