### ISSUE TITLE
The field "reply_to_message_id" is not available ( or maybe I cannot see)  in the Message object the response of the getting the emails from the java SDK. Can you help me with this?

### ISSUE THREAD

**Issue by rohitpandit** [nylas/nylas-java#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atejada** [comment]
Hello @rohitpandit, the field **reply_to_message_id** is on the **Draft** object and not in the **messages** object:

```
Draft draft = new Draft();
draft.setReplyToMessageId("<MESSAGE_ID>");
```

You get the **id** from the message object and use it on the draft

```
Messages messages = account.messages();
RemoteCollection<Message> messageList = messages.list(new MessageQuery().in("inbox").limit(1));
for(Message email : messageList){
    System.out.println(email.getId());
}
```

**Comment by atejada** [comment]
@rohitpandit Sorry 😢 You're right, I realized that the field is actually missing...will fix it and get a PR for it 😄 Give me a couple of days as I'm busy with work
