### ISSUE TITLE
FindAttachmentQueryParams builder returns FindEventQueryParams

### ISSUE THREAD

**Issue by flokle** [nylas/nylas-java#207]
**Describe the bug**
The return type of FindAttachmentQueryParams.Builder.build() method is defined as FindEventQueryParams

**To Reproduce**
See code: https://github.com/nylas/nylas-java/blob/main/src/main/kotlin/com/nylas/models/FindAttachmentQueryParams.kt

**Expected behavior**
Should return FindAttachmentQueryParams

**SDK Version:**
2.1.0

**Comment by ashryanbeats** [comment]
Passed along to the team. Thanks for reporting!

**Comment by atejada** [comment]
Addressed with PR https://github.com/nylas/nylas-java/pull/208 Thanks for reporting @flokle 😊

**Comment by mrashed-dev** [comment]
Thanks for the fix @atejada!

@flokle fix will be included in the next release!
