### ISSUE TITLE
getReplyToMessageId is Not available in the Message object ( when getting the emails) , can you please add it

### ISSUE THREAD

**Issue by rohitpandit** [nylas/nylas-java#230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrashed-dev** [comment]
Thanks for opening the issue @rohitpandit we will look into this and provide you with an update as soon as we can.

**Comment by mrashed-dev** [comment]
Hey @rohitpandit just looking through your request again, you mention you want to get a replyToMessageId? Are you looking for an ID to reply to with a new message or do you want the ID of the message this message is replying to? Thanks!

**Comment by mrashed-dev** [comment]
Closing this ticket due to inactivity, please reopen if this issue comes up again.
