### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by sausageRoll** [nylas/nylas-java#3]
Hey team! What do you think about java async client with https://projectreactor.io/

**Comment by ddlatham** [comment]
Hi @sausageRoll - thanks for the suggestion!

We've been considering supporting an async API since the beginning, but started with a sync API for simplicity.

Can you describe how you're using the SDK and how an Async API would help for your case?

**Comment by sausageRoll** [comment]
We have an app for accessing users' data in their mail accounts. 
Async SDK can help us to save resources

**Comment by ddlatham** [comment]
Ok.  I think this is something we'd consider in the future, especially if we get enough interest for it, but not ready to do right now.  If you're willing to share any more details that would be helpful.

For example, are you already using Reactor and would appreciate a compatible implementation?  When you mention saving resources, is it that you are concerned about the overhead of threads?  Do you have a expected level of concurrency?  Or is it more about fitting into the style of programming you are already using?

**Comment by sausageRoll** [comment]
In an app if I decided to use non-blocking api then everything should be in non-blocking manner otherwise the app will run out of free threads
It's very important for http calls as they can be very expensive in terms of latency

**Comment by ddlatham** [comment]
No immediate plans, but definitely still interested to hear how much demand there is for an Async API, so for future users, please add a 👍 or a comment.

Also looking forward to Java's Project Loom some day.
http://cr.openjdk.java.net/~rpressler/loom/loom/sol1_part1.html
