### ISSUE TITLE
Cannot create Event.Recurrence

### ISSUE THREAD

**Issue by vishnuinfrrd** [nylas/nylas-java#4]
Currently, in the Java SDK v1.0.0, **com.nylas.Event.Recurrence** object only has an empty constructor. How can we create a new _Recurrence_ object and set it to an event?

**Comment by ddlatham** [comment]
Thanks, @vishnuinfrrd, for reporting the issue.  We will address it shortly.

**Comment by ddlatham** [comment]
Fixed in version 1.0.1
