### ISSUE TITLE
Adding calendar to MS/Outlook provider causes error, Google does not.

### ISSUE THREAD

**Issue by burtonrhodes** [nylas/nylas-java#92]
When adding a new calendar for an Outlook provider, and the "description" is set, I get an error and the calendar is not added. The error is specific and tells me that I can't add this calendar due to setting the "description" (and apparently the timezone or location) which is helpful.  However, I feel like this should be a warning, not an error. 

One of the main advantages of a standardized API is not having to modify code based off the provider.  So now when adding a Calendar I will need to check the provider first before adding certain elements descriptive elements. Is there something I'm missing on why this request becomes a full-stop error instead of just adding the calendar without a description? Curious your thoughts on is the API should be modified for this scenario.

Code
>    Calendar calendar = new Calendar();
>    calendar.setName("My Calendar");
>    calendar.setDescription("Calendar for UserId: " + appUserId);
>    calendar.getMetadata().put("UserId", appUserId.toString());
>    calendar = this.account.calendars().create(calendar);

Error when provider is MS/Outlook
`
ERROR com.nylas.RequestFailedException: statusCode=400, type=invalid_request_error, message=This provider only supports 'name'; does not support 'timezone', 'description', nor 'location'.
	at com.nylas.RequestFailedException.parseErrorResponse(RequestFailedException.java:84)
	at com.nylas.NylasClient.throwAndCloseOnFailedRequest(NylasClient.java:255)
	at com.nylas.NylasClient.executeRequest(NylasClient.java:239)
	at com.nylas.NylasClient.executeRequestWithAuth(NylasClient.java:204)
	at com.nylas.NylasClient.executePost(NylasClient.java:168)
	at com.nylas.RestfulDAO.create(RestfulDAO.java:88)
	at com.nylas.RestfulDAO.create(RestfulDAO.java:77)
	at com.nylas.RestfulDAO.create(RestfulDAO.java:69)
	at com.nylas.Calendars.create(Calendars.java:36)
`

Thanks!

**Comment by mrashed-dev** [comment]
@burtonrhodes Thank you for opening this issue and sorry for the delay. I've raised this issue internally and in our next major update for our API we are tackling issues like this by using standardized fields valid for all providers! Unfortunately we are not providing support for this in the existing v2.x of the Nylas API. When I have more news to share I will pass them along here to this ticket. Thanks again for your patience on this.
